<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
<script src="<?php echo __ROOT__;?>/classLibs/jquery/jquery.js"></script>
<script src="<?php echo __ROOT__;?>/classLibs/bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo __ROOT__;?>/classLibs/waterfall/waterfall.js"></script>
<script src="<?php echo __ROOT__;?>/classLibs/cursorInsert/insert.js"></script>
<link href="<?php echo __ROOT__;?>/classLibs/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<style type="text/css">
*{margin:0px;padding:0px;}
li{list-style:none;}
#box{
	width:300px;
	height:300px;
	border:1px solid #ddd;
	box-shadow:0px 0px 5px #ddd;
	margin:30px auto;
	padding:10px;
}
#box textarea{
	width:280px;
	height:120px;
}
#phiz{
	width:300px;
	height:120px;
	float:left;
	margin-left:0px;
}
#phiz li{
	width:30px;
	float:left;
	height:30px;
}
</style>
<script>
	$(function(){
		$('#phiz li').click(function(){
			var title = '['+$(this).find('img').attr('title')+']';
			$('#content').insertAtCaret(title);
		})
	})



</script>
</head>
<body>
	<div id="box">
		<form action="<?php echo __APP__;?>?c=Index&m=add" method="post">
			<textarea id="content" name="content"></textarea>
			<ul id="phiz">
				<li><img src="./public/phiz/hehe.gif" alt="呵呵" title="呵呵" /></li>
                <li><img src="./public/phiz/xixi.gif" alt="嘻嘻" title="嘻嘻" /></li>
                <li><img src="./public/phiz/haha.gif" alt="哈哈" title="哈哈" /></li>
                <li><img src="./public/phiz/keai.gif" alt="可爱" title="可爱" /></li>
                <li><img src="./public/phiz/kelian.gif" alt="可怜" title="可怜" /></li>
                <li><img src="./public/phiz/wabisi.gif" alt="挖鼻屎" title="挖鼻屎" /></li>
                <li><img src="./public/phiz/chijing.gif" alt="吃惊" title="吃惊" /></li>
                <li><img src="./public/phiz/haixiu.gif" alt="害羞" title="害羞" /></li>
                <li><img src="./public/phiz/jiyan.gif" alt="挤眼" title="挤眼" /></li>
                <li><img src="./public/phiz/bizui.gif" alt="闭嘴" title="闭嘴" /></li>
                <li><img src="./public/phiz/bishi.gif" alt="鄙视" title="鄙视" /></li>
                <li><img src="./public/phiz/aini.gif" alt="爱你" title="爱你" /></li>
                <li><img src="./public/phiz/lei.gif" alt="泪" title="泪" /></li>
                <li><img src="./public/phiz/touxiao.gif" alt="偷笑" title="偷笑" /></li>
                <li><img src="./public/phiz/qinqin.gif" alt="亲亲" title="亲亲" /></li>
                <li><img src="./public/phiz/shengbin.gif" alt="生病" title="生病" /></li>
                <li><img src="./public/phiz/taikaixin.gif" alt="太开心" title="太开心" /></li>
                <li><img src="./public/phiz/ldln.gif" alt="懒得理你" title="懒得理你" /></li>
                <li><img src="./public/phiz/youhenhen.gif" alt="右哼哼" title="右哼哼" /></li>
                <li><img src="./public/phiz/zuohenhen.gif" alt="左哼哼" title="左哼哼" /></li>
                <li><img src="./public/phiz/xiu.gif" alt="嘘" title="嘘" /></li>
                <li><img src="./public/phiz/shuai.gif" alt="衰" title="衰" /></li>
                <li><img src="./public/phiz/weiqu.gif" alt="委屈" title="委屈" /></li>
                <li><img src="./public/phiz/tu.gif" alt="吐" title="吐" /></li>
                <li><img src="./public/phiz/dahaqian.gif" alt="打哈欠" title="打哈欠" /></li>
                <li><img src="./public/phiz/baobao.gif" alt="抱抱" title="抱抱" /></li>
                <li><img src="./public/phiz/nu.gif" alt="怒" title="怒" /></li>
                <li><img src="./public/phiz/yiwen.gif" alt="疑问" title="疑问" /></li>
                <li><img src="./public/phiz/canzui.gif" alt="馋嘴" title="馋嘴" /></li>
                <li><img src="./public/phiz/baibai.gif" alt="拜拜" title="拜拜" /></li>
                <li><img src="./public/phiz/sikao.gif" alt="思考" title="思考" /></li>
                <li><img src="./public/phiz/han.gif" alt="汗" title="汗" /></li>
                <li><img src="./public/phiz/kun.gif" alt="困" title="困" /></li>
                <li><img src="./public/phiz/shuijiao.gif" alt="睡觉" title="睡觉" /></li>
                <li><img src="./public/phiz/qian.gif" alt="钱" title="钱" /></li>
                <li><img src="./public/phiz/shiwang.gif" alt="失望" title="失望" /></li>
			</ul>
			<input class='btn' type="submit" value="提交">
		</form>
	</div>
</body>
</html>