<?php 
$config['skin']=array(
	'suit'=>array(
		'tab_nosep'=>array(
			'推荐',
			'七天换装',
			'会员',
			'动态'
			),
		'templete_list'=>array(
			'skin_001'=>'雨夜',
			'skin_002'=>'太空',
			'skin_003'=>'团团圆圆',
			'skin_004'=>'神偷奶爸2',
			'skin_005'=>'漓彩',
			'skin_006'=>'保护北冰洋',
			'skin_007'=>'带TA回家',
			'skin_008'=>'下雪啦'
			)
		),
	'bg'=>array(
		'tab_nosep'=>array(
			'童趣',
			'时尚',
			'校园',
			'节日',
			'经典'
			),
		'templete_list'=>array(
			'skin_001'=>'风轻云淡',
			'skin_002'=>'我们结婚吧',
			'skin_003'=>'猫趣',
			'skin_004'=>'复古',
			'skin_005'=>'漓彩',
			'skin_006'=>'Iam 80后',
			'skin_007'=>'带TA回家',
			'skin_008'=>'梦幻'
			)
		),
	'cover'=>array(
		'tab_nosep'=>array(
			'推荐',
			'卡通',
			'田园',
			'时尚',
			'萌',
			'静物',
			'风景'
			),
		'templete_list'=>array(
			'001_s'=>'弹钢琴的小老鼠',
			'002_s'=>'蝴蝶纷飞',
			'003_s'=>'绮丽街景',
			'004_s'=>'绿芽',
			)
		),
	'style'=>array(
		'tab_nosep'=>array(
			'自定义模板',
			'自定义封面图'
			),
		'templete_list'=>array(
			'1'=>'',
			'2'=>'',
			'3'=>'',
			'4'=>'',
			'5'=>'',
			'6'=>'',
			'7'=>'',
			'8'=>'',
			'9'=>'',
			'10'=>''
			)
		)
);